[supervisord]
nodaemon=true

[program:xvfb]
command=/usr/bin/Xvfb :1 -screen 0 1024x768x24

[program:fluxbox]
command=/usr/bin/fluxbox -display :1
autorestart=true
startretries=3

[program:x11vnc]
command=/usr/bin/x11vnc -display :1 -nopw -forever -rfbport 5900
autorestart=true
startretries=3

[program:novnc]
command=/usr/local/bin/noVNC/utils/launch.sh --vnc localhost:5900 --listen 6080 --web /usr/local/lib/python3.10/site-packages/noVNC/ --cert /dev/null
autorestart=true
startretries=3
